package com.alkemy.ong.dto;

import io.swagger.v3.oas.annotations.media.Schema;
import lombok.Getter;
import lombok.RequiredArgsConstructor;
import lombok.Setter;
import org.springframework.lang.Nullable;

@RequiredArgsConstructor
@Getter @Setter
public class ActivityDto {
    @Schema(name = "id", example = "1", type = "Long", description = "id: autogenerated", hidden = true)
    private Long id;
    @Schema(name = "name",example = "nameActivity",type = "String",description = "description : name of the activity")
    private String name;
    @Schema(name = "content",example = "contentActivity", type = "String",description = "description : content of the activity")
    private String content;
    @Schema(name = "image",example = "url.com/imageActivity.jpg", type = "String",description = "description : image of the activity")
    private String image;
}
