package com.alkemy.ong.dto;
import io.swagger.v3.oas.annotations.media.Schema;
import lombok.*;
import javax.validation.constraints.NotBlank;

@Getter
@Setter
@RequiredArgsConstructor
public class CategoryDto {

    @Schema(name = "id", example = "1", type = "Long", description = "id: autogenerated", hidden = true)
    private Long id;
    @Schema(name = "name", example = "nameCategory", type = "String", description = "description : name of the activity (not allows null)")
    @NotBlank(message = "Name is mandatory")
    private String name;
    @Schema(name = "description", example = "descriptionCategory", type = "String", description = "description: description about the category")
    private String description;
    @Schema(name = "image", example = "url.com/imageCategory.jpg", type = "String", description = "description: image of the category")
    private String image;

}
