package com.alkemy.ong.dto;

import io.swagger.v3.oas.annotations.media.Schema;
import lombok.Getter;
import lombok.RequiredArgsConstructor;
import lombok.Setter;

@Getter
@Setter
@RequiredArgsConstructor
public class CommentDto {
    @Schema(name = "id", example = "1", type = "Long", description = "id: autogenerated")
    private Long id;
    @Schema(name = "body", example = "i love the ONG!", type = "String", description = "description: comment from user about the ONG")
    private String body;
    @Schema(name = "userId", example = "3", type = "Long", description = "description: id of user linked to this comment")
    private Long user_id;
    @Schema(name = "newsId", example = "7", type = "Long", description = "description: id of news linked to this comment")
    private Long news_id;
}
