package com.alkemy.ong.dto;

import com.fasterxml.jackson.annotation.JsonInclude;
import io.swagger.v3.oas.annotations.media.Schema;
import lombok.Getter;
import lombok.RequiredArgsConstructor;
import lombok.Setter;

import javax.validation.constraints.NotNull;

@Getter
@Setter
@RequiredArgsConstructor
@JsonInclude(JsonInclude.Include.NON_NULL)
public class ContactDto {

    @Schema(name = "id", example = "1", type = "Long", description = "id: autogenerated)")
    @NotNull
    private Long id;
    @Schema(name = "name", example = "Agustin", type = "String", description = "description: name of the contact (not allow null)")
    @NotNull
    private String name;
    @Schema(name = "phone", example = "1145386540", type = "String", description = "description: phone of the contact (not allow null)")
    @NotNull
    private String phone;
    @Schema(name = "email", example = "agustin@mail.com", type = "String", description = "description: emil of the contact (not allow null)")
    @NotNull
    private String email;
    @Schema(name = "message", example = "this ONG is fantastic", type = "String", description = "description: message given by the contact (not allow null)")
    @NotNull
    private String message;

}
