package com.alkemy.ong.dto;

import io.swagger.v3.oas.annotations.media.Schema;
import lombok.Getter;
import lombok.RequiredArgsConstructor;
import lombok.Setter;
import java.time.LocalDateTime;

@Getter
@Setter
@RequiredArgsConstructor
public class MemberDto {
        @Schema(name = "id", example = "1", type = "integer", nullable = false, description = "id: autogenerated", hidden = true)
        private Long id;
        @Schema(name = "name", example = "Andres Rodriguez", nullable = false, description = "name: cannot allow null")
        private String name;
        @Schema(name = "facebookUrl", type = "facebook.com/Andres", nullable = true, example = "facebookAndres")
        private String facebookUrl;
        @Schema(name = "instagramUrl", type = "instagram.com/Andres", nullable = true, example = "instagramAndres")
        private String instagramUrl;
        @Schema(name = "linkedinUrl", type = "linkedin.com/Andres", nullable = true, example = "linkedinAndres")
        private String linkedinUrl;
        @Schema(name = "image", type = "String", example = "ImageUrlAndres", nullable = true, description = "image: cannot allow null")
        private String image;
        @Schema(name = "description", type = "DescriptionAndres", nullable = true, example = "Hello my name is Andres")
        private String description;
        @Schema(name = "creationDate", type = "LocalDateTime", nullable = false, description = "creationDate: date of creation is autogenerated", hidden = true)
        private LocalDateTime creationDate;
        @Schema(name = "updateDate", type = "LocalDateTime", nullable = false, description = "updateDate: date of update is autogenerated", hidden = true)
        private LocalDateTime updateDate;
}
