package com.alkemy.ong.dto;

import io.swagger.v3.oas.annotations.media.Schema;
import lombok.Getter;
import lombok.RequiredArgsConstructor;
import lombok.Setter;


@Getter
@Setter
@RequiredArgsConstructor
public class NewsDto {

    @Schema(name = "id", example = "1", type = "Long", description = "id: autogenerated", hidden = true)
    private Long id;

    @Schema(name = "name",example = "",type = "String",description = "description : name of the news")
    private String name;

    @Schema(name = "content",example = "", type = "String",description = "description : content of the news")
    private String content;

    @Schema(name = "image",example = "url.com/image.jpg", type = "String",description = "description : image of the news")
    private String image;

    @Schema(name = "categoryId",example = "1", type = "Long",description = "description : id: autogenerated", hidden = true)
    private Long categoryId;

}
