package com.alkemy.ong.dto;
import io.swagger.v3.oas.annotations.media.Schema;
import lombok.Getter;
import lombok.RequiredArgsConstructor;
import lombok.Setter;

import javax.validation.constraints.NotNull;

@Getter
@Setter
@RequiredArgsConstructor
public class SlideDto {
    @Schema(name = "id", example = "1", type = "Long", description = "id: autogenerated", hidden = true)
    private Long id;
    @Schema(name = "imageUrl", example = "url.com/image.jpg", type = "String", description = "description : slide image url (not allows null)")
    @NotNull(message = "The image cannot be empty")
    private String imageUrl;
    @Schema(name = "text", example = "Welcome to the web side!",nullable = true, type = "String", description = "description : slide text")
    private String text;
    @Schema(name = "order", example = "1", type = "Integer", description = "description : slider order",nullable = true)
    private Integer order;
    @Schema(name = "organization_id",example = "1",type = "Long",hidden = true)
    @NotNull(message = "The organization id cannot be empty")
    private Long organization_id;

}