package com.alkemy.ong.dto;
import io.swagger.v3.oas.annotations.media.Schema;
import lombok.Getter;
import lombok.RequiredArgsConstructor;
import lombok.Setter;
@Getter
@Setter
@RequiredArgsConstructor
public class SlideDto {
    @Schema(name = "id", example = "1", type = "integer", nullable = false, description = "id: autogenerated", hidden = true)
    private Long id;
    private String imageUrl;
    private String text;
    private Integer order;
    private Long organization_id;

}