package com.alkemy.ong.dto;

import javax.validation.constraints.NotNull;

import io.swagger.v3.oas.annotations.media.Schema;
import lombok.*;

@Getter
@Setter
public class TestimonialDto {
    @Schema(name = "id", example = "1", type = "integer", description = "id: autogenerated", hidden = true)
    private Long id;
    @Schema(name = "name", example = "Agostina Suarez", description = "description : testimonial name (not allows null)")
    @NotNull(message = "The name cannot be empty")
    private String name;
    @Schema(name = "image", type = "String", example = "url.com/image.jpg", description = "description : testimonial image (cannot allow null)")
    private String image;
    @Schema(name = "content", type = "String", nullable = true, example = "I love this ONG",description = "description: testimonial content")
    @NotNull(message = "The content cannot be empty")
    private String content;
}
